### ISSUE TITLE
Deploy 2024-04-03

### ISSUE THREAD

**Issue by gabmontes** [hemilabs/pure.finance#10]
@dhidalgX please deploy the Hemi PF app. Instructions in the [README.md](https://github.com/hemilabs/pure.finance/blob/master/README.md#deployment) file.

**Comment by dhidalgX** [comment]
@gabmontes Please create a running docker image to be deployed.
cc'd: @jcvernaleo

**Comment by gabmontes** [comment]
@dhidalgX this is a 100% static file. What do we need a Docker image for?

**Comment by dhidalgX** [comment]
Oh ok, thanks for clarifying.

**Comment by dhidalgX** [comment]
So in this case, i will just need to focus on the deployment portion... 
[Set the following environment variables: BASE_NODE_URL, MNEMONIC. Then run the tests:](https://github.com/hemilabs/pure.finance/blob/master/README.md#deployment)

@gabmontes please confirm. 
cc'd: @jcvernaleo

**Comment by gabmontes** [comment]
@dhidalgX yes. That's exactly what I requested in https://github.com/hemilabs/pure.finance/issues/10#issue-2223650105. 😄

**Comment by dhidalgX** [comment]
@jcvernaleo Do we have a desire link for pure.finance? 

f.e: 
hemi.xyz/pure.finance ?

**Comment by jcvernaleo** [comment]
Yes, that works for me.

**Comment by gabmontes** [comment]
That may not work. The site is configured to be built and hosted in a domain or a subdomain, not below a path.

Let's consider tools.hemi.xyz or something like that.

**Comment by dhidalgX** [comment]
@gabmontes There is a business need, as a understand to use path related links instead of subdomains. @jcvernaleo Maybe you could explain better. 
From our side, we have not setup any path related links so far, all of them are subdomains.

**Comment by gabmontes** [comment]
@dhidalgX ok. Proceed with the deploy. If the app does not render properly, we will fix that.

**Comment by jcvernaleo** [comment]
The reason for the desired URL was at @philgomes 's request for SEO related black magic.

But if fixing PF for that is too much work we can always do subdomain for this as a special case.

**Comment by gabmontes** [comment]
Is ok. Let's try and if fails, we will fix the problem. I think it is just a few params in Next's config.

**Comment by gabmontes** [comment]
@dhidalgX please proceed with the deploy once #12 is merged. Set `BASE_PATH` at build time as described in the docs.

**Comment by dhidalgX** [comment]
@jcvernaleo @gabmontes I will need to create some secrets for deployment automation and admin access to https://github.com/hemilabs/pure.finance repo

**Comment by dhidalgX** [comment]
@jcvernaleo @gabmontes for now https://purefinance.hemi.xyz is enabled, still need to work on path links as required.

**Comment by gabmontes** [comment]
@dhidalgX this is done, right?

**Comment by dhidalgX** [comment]
@gabmontes Yes, this issue is solved, was realated to SSH keys with Hostinger.
