### ISSUE TITLE
Second design pass

### ISSUE THREAD

**Issue by leanazulyoro** [hemilabs/pure.finance#32]
Let's further improve the style of the app to be closer to other Hemi's apps (portal, uniswap)

**Describe the solution you'd like**

- header has way too many space on top, make it consistent with the rest of the hemi ecosystem.
- I suggest having a similar design to uniswap, with the grey box as the content background, leaving the logo on top (TBD with designer), and the footer as well. See screenshot below for reference.
- the navigation tabs need some indication of which tab/page is selected. 

<img width="783" alt="Captura de pantalla 2024-04-19 a la(s) 13 00 27" src="https://github.com/hemilabs/pure.finance/assets/1864435/0d0f4a65-3bcc-457b-bf8a-d604e877ec50">

**Comment by rmilrad** [comment]
Tracking in separate issue.
