### ISSUE TITLE
Token input overlap

### ISSUE THREAD

**Issue by gabmontes** [hemilabs/pure.finance#50]
The token address and token name overlap in the token input.

## Screenshots

This is Hemi's flavor of the input:

![Image](https://github.com/user-attachments/assets/db1b944f-0e91-4863-a6c9-12fbd2d3c90e)

This is the original PF's design:

![Image](https://github.com/user-attachments/assets/c8d78f1f-aaf2-4d5c-8198-cb8f3cedc9d6)

## Steps to Reproduce

1. Write any known token address or symbol. 
2. 💥

**Comment by dvnahuel** [comment]
As a quick fix, we can add a background color to the token symbol as show in the screenshot:
![Image](https://github.com/user-attachments/assets/e56555a3-99f6-43cb-a28e-c9b803712857)
